/*
 * This source file was generated by the Gradle 'init' task
 */
package q5;
import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);
        int x = 5;
        scanIn.close();
        for (int i = 1; i <= x; i++) {

            for (int j = 1; j <= i; j++) {
                System.out.print("*");
            }
            System.out.println();
        }
        for (int i = 4-1; i >= 0; i--) {

            for (int j = 0; j <= i-1; j++) {
                System.out.print("*");
            }
            System.out.println();
        }

    }
}