/*
 * This source file was generated by the Gradle 'init' task
 */
package q3;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner scanIn = new Scanner(System.in);
        System.out.print("Input your salary : ");
        double a = scanIn.nextDouble();
        scanIn.close();
        if(a <= 15000) {
            a = a * 0.05;
        } else {
            a = 15000 * 0.05;
        }
        System.out.print("Your Welfare is "+ a + " Baht");
    }
}