/*
 * This source file was generated by the Gradle 'init' task
 */

 package assignment;
 import java.util.Scanner;
 
 public class App {
     public String getGreeting() {
         return "Hello World!";
     }
 
     public static void main(String[] args) {
         Scanner scanIn = new Scanner(System.in);
         System.out.print("Input P : ");
         int P = scanIn.nextInt();
         System.out.print("Input Q : ");
         int Q = scanIn.nextInt();
         scanIn.close();
         int PQ = P ^ Q;
         if (PQ > 1 || PQ < 0) {
             System.out.println("Error");
         } else {
             System.out.println(P + " XOR " + Q + " = " + PQ);
         }
     }
 }